version = 5.2.2
archive_dir = /etc/letsencrypt/archive/crm.qazaq.education
cert = /etc/letsencrypt/live/crm.qazaq.education/cert.pem
privkey = /etc/letsencrypt/live/crm.qazaq.education/privkey.pem
chain = /etc/letsencrypt/live/crm.qazaq.education/chain.pem
fullchain = /etc/letsencrypt/live/crm.qazaq.education/fullchain.pem
[renewalparams]
account = ac5949eb19b463713ea45fe2aee3668e
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
crm.qazaq.education = /var/www/certbot
