<?php

namespace app\models;

use app\traits\AttributesToInfoTrait;
use Yii;
use yii\web\UploadedFile;
use app\components\ActiveRecord;

/**
 * This is the model class for table "settings".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $logo
 * @property string|null $phones
 * @property string|null $address
 * @property string|null $email
 * @property string|null $facebook
 * @property string|null $schedule
 * @property string|null $whatsapp
 * @property string|null $instagram
 * @property string|null $two_gis
 * @property string|null $map_x
 * @property string|null $map_y
 * @property string|null $url
 * @property string|null $project_amount
 * @property string|null $energy_subject_amount
 * @property string|null $percent_energy
 * @property string $info
 */
class Settings extends ActiveRecord
{
    public $image;
    public $phoneList;

    use AttributesToInfoTrait;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'settings';
    }

    public function attributesToInfo()
    {
        return [
            'email',
            // Соцсети (хранятся в info если нет колонок в БД)
            'telegram',
            'youtube',
            'instagram',
            'whatsapp',
            'facebook',
            // Контакты
            'working_hours',
            // Статистика лендинга
            'stat_centers_count',
            'stat_centers_label',
            'stat_pupils_count',
            'stat_pupils_label',
            'stat_satisfaction_count',
            'stat_satisfaction_label',
            // SEO
            'meta_title',
            'meta_description',
            'meta_keywords',
            // Информация о системе (features page)
            'features_hero_title',
            'features_hero_subtitle',
            'feature_1_title',
            'feature_1_description',
            'feature_2_title',
            'feature_2_description',
            'feature_3_title',
            'feature_3_description',
            'feature_4_title',
            'feature_4_description',
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['phones'], 'string'],
            ['email', 'email'],
            // Соцсети и контакты
            [['telegram', 'youtube', 'instagram', 'whatsapp', 'facebook', 'working_hours'], 'string', 'max' => 255],
            // Статистика
            [['stat_centers_count', 'stat_centers_label', 'stat_pupils_count',
              'stat_pupils_label', 'stat_satisfaction_count', 'stat_satisfaction_label'], 'string', 'max' => 50],
            // SEO
            [['meta_title'], 'string', 'max' => 70],
            [['meta_description'], 'string', 'max' => 160],
            [['meta_keywords'], 'string', 'max' => 255],
            // Features
            [['features_hero_title', 'features_hero_subtitle'], 'string', 'max' => 255],
            [['feature_1_title', 'feature_2_title', 'feature_3_title', 'feature_4_title'], 'string', 'max' => 100],
            [['feature_1_description', 'feature_2_description', 'feature_3_description', 'feature_4_description'], 'string', 'max' => 500],
        ];
    }

    public function loadDefaultValues($skipIfSet = true)
    {
        $this->phoneList = isset($this->phones) ? json_decode($this->phones): [''];
        if (!$this->url){
            $this->url = BackendHelper::getUrl();
        }
        return parent::loadDefaultValues($skipIfSet); // TODO: Change the autogenerated stub
    }

    public function getPhoneNumbers(){
        return isset($this->phones) ? json_decode($this->phones): [];
    }



    /**
     * @param UploadedFile $file
     */
    private function saveFile(UploadedFile $file){
        $link = ($this->logo) ? : null;
        $this->image = $file;
        if ($this->validate(['file'])) {
            $rand = uniqid(rand(), true);
            $dir = Yii::getAlias('@frontend/web/docs/settings/');
            $dir2 = Yii::getAlias('docs/settings/');
            $fileName = $rand . '.' . $this->image->extension;
            $this->image->saveAs($dir . $fileName);
            $this->image = $fileName; // без этого ошибка
            $link = '/'.$dir2 . $fileName;
        }

        $this->logo = $link;
        $this->image = null;
    }

    /**
     * @param bool $runValidation
     * @param null $attributeNames
     * @return bool
     */
    public function save($runValidation = true, $attributeNames = null)
    {
        $file = UploadedFile::getInstance($this, "image");
        if ($file && $file->tempName) {
            $this->saveFile($file);
        }
        if ($this->phoneList) {
            $phones = [];
            foreach ($this->phoneList as $phone){
                if (strlen(trim($phone)) > 0){
                    $phones[] = trim($phone);
                }
            }
            $this->phones = json_encode($phones);
        }
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }

    public function getMainPhone(){
        $phoneNumbers = $this->getPhoneNumbers();
        return  $phoneNumbers && sizeof($phoneNumbers) > 0 ? $phoneNumbers[0] : '';
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Название компании'),
            'image' => Yii::t('app', 'Логотип'),
            'logo' => Yii::t('app', 'Логотип'),
            'phones' => Yii::t('app', 'Телефоны'),
            'address' => Yii::t('app', 'Адрес'),
            'facebook' => Yii::t('app', 'Ссылка Facebook'),
            'instagram' => Yii::t('app', 'Ссылка Instagram'),
            'whatsapp' => Yii::t('app', 'Ссылка Whatsapp'),
            'two_gis' => Yii::t('app', 'Ссылка 2gis'),
            'map_x' => Yii::t('app', 'Широта в 2gis'),
            'map_y' => Yii::t('app', 'Долгота в 2gis'),
            'schedule' => Yii::t('app', 'График работы'),
            'email' => Yii::t('app', 'E-mail'),
            'url' => Yii::t('app', 'Url сайта'),
            'percent_energy' => Yii::t('app', 'Снижение энергоёмкости ВВП РК'),
            'energy_subject_amount' => Yii::t('app', 'Потребление энергии субъектами ГЭР'),
            'project_amount' => Yii::t('app', 'Количество проектов по РК'),
            'dir_email' => Yii::t('app', 'Почта председателя'),
            'kadr_email' => Yii::t('app', 'Почта кадровика'),
            // Соцсети
            'telegram' => Yii::t('app', 'Telegram'),
            'youtube' => Yii::t('app', 'YouTube'),
            // Контакты
            'working_hours' => Yii::t('app', 'Часы работы'),
            // Статистика лендинга
            'stat_centers_count' => Yii::t('app', 'Количество центров'),
            'stat_centers_label' => Yii::t('app', 'Подпись (центры)'),
            'stat_pupils_count' => Yii::t('app', 'Количество учеников'),
            'stat_pupils_label' => Yii::t('app', 'Подпись (ученики)'),
            'stat_satisfaction_count' => Yii::t('app', 'Процент довольных'),
            'stat_satisfaction_label' => Yii::t('app', 'Подпись (довольные)'),
            // SEO
            'meta_title' => Yii::t('app', 'Meta Title'),
            'meta_description' => Yii::t('app', 'Meta Description'),
            'meta_keywords' => Yii::t('app', 'Meta Keywords'),
            // Features
            'features_hero_title' => Yii::t('app', 'Заголовок Features'),
            'features_hero_subtitle' => Yii::t('app', 'Подзаголовок Features'),
            'feature_1_title' => Yii::t('app', 'Функция 1 - Заголовок'),
            'feature_1_description' => Yii::t('app', 'Функция 1 - Описание'),
            'feature_2_title' => Yii::t('app', 'Функция 2 - Заголовок'),
            'feature_2_description' => Yii::t('app', 'Функция 2 - Описание'),
            'feature_3_title' => Yii::t('app', 'Функция 3 - Заголовок'),
            'feature_3_description' => Yii::t('app', 'Функция 3 - Описание'),
            'feature_4_title' => Yii::t('app', 'Функция 4 - Заголовок'),
            'feature_4_description' => Yii::t('app', 'Функция 4 - Описание'),
        ];
    }
}
