<?php

namespace app\models;

use app\traits\AttributesToInfoTrait;
use Yii;
use yii\web\UploadedFile;
use app\components\ActiveRecord;

/**
 * This is the model class for table "settings".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $logo
 * @property string|null $phones
 * @property string|null $address
 * @property string|null $email
 * @property string|null $facebook
 * @property string|null $schedule
 * @property string|null $whatsapp
 * @property string|null $instagram
 * @property string|null $two_gis
 * @property string|null $map_x
 * @property string|null $map_y
 * @property string|null $url
 * @property string|null $project_amount
 * @property string|null $energy_subject_amount
 * @property string|null $percent_energy
 * @property string $info
 */
class Settings extends ActiveRecord
{
    public $image;
    public $phoneList;

    use AttributesToInfoTrait;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'settings';
    }

    public function attributesToInfo()
    {
        return [
            'email',
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['phones'], 'string'],
            ['email','email'],
        ];
    }

    public function loadDefaultValues($skipIfSet = true)
    {
        $this->phoneList = isset($this->phones) ? json_decode($this->phones): [''];
        if (!$this->url){
            $this->url = BackendHelper::getUrl();
        }
        return parent::loadDefaultValues($skipIfSet); // TODO: Change the autogenerated stub
    }

    public function getPhoneNumbers(){
        return isset($this->phones) ? json_decode($this->phones): [];
    }



    /**
     * @param UploadedFile $file
     */
    private function saveFile(UploadedFile $file){
        $link = ($this->logo) ? : null;
        $this->image = $file;
        if ($this->validate(['file'])) {
            $rand = uniqid(rand(), true);
            $dir = Yii::getAlias('@frontend/web/docs/settings/');
            $dir2 = Yii::getAlias('docs/settings/');
            $fileName = $rand . '.' . $this->image->extension;
            $this->image->saveAs($dir . $fileName);
            $this->image = $fileName; // без этого ошибка
            $link = '/'.$dir2 . $fileName;
        }

        $this->logo = $link;
        $this->image = null;
    }

    /**
     * @param bool $runValidation
     * @param null $attributeNames
     * @return bool
     */
    public function save($runValidation = true, $attributeNames = null)
    {
        $file = UploadedFile::getInstance($this, "image");
        if ($file && $file->tempName) {
            $this->saveFile($file);
        }
        if ($this->phoneList) {
            $phones = [];
            foreach ($this->phoneList as $phone){
                if (strlen(trim($phone)) > 0){
                    $phones[] = trim($phone);
                }
            }
            $this->phones = json_encode($phones);
        }
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }

    public function getMainPhone(){
        $phoneNumbers = $this->getPhoneNumbers();
        return  $phoneNumbers && sizeof($phoneNumbers) > 0 ? $phoneNumbers[0] : '';
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Название компании'),
            'image' => Yii::t('app', 'Логотип'),
            'logo' => Yii::t('app', 'Логотип'),
            'phones' => Yii::t('app', 'Телефоны'),
            'address' => Yii::t('app', 'Адрес'),
            'facebook' => Yii::t('app', 'Ссылка Facebook'),
            'instagram' => Yii::t('app', 'Ссылка Instagram'),
            'whatsapp' => Yii::t('app', 'Ссылка Whatsapp'),
            'two_gis' => Yii::t('app', 'Ссылка 2gis'),
            'map_x' => Yii::t('app', 'Широта в 2gis'),
            'map_y' => Yii::t('app', 'Долгота в 2gis'),
            'schedule' => Yii::t('app', 'График работы'),
            'email' => Yii::t('app', 'E-mail'),
            'url' => Yii::t('app', 'Url сайта'),
            'percent_energy' => Yii::t('app', 'Снижение энергоёмкости ВВП РК'),
            'energy_subject_amount' => Yii::t('app', 'Потребление энергии субъектами ГЭР'),
            'project_amount' => Yii::t('app', 'Количество проектов по РК'),
            'dir_email' => Yii::t('app', 'Почта председателя'),
            'kadr_email' => Yii::t('app', 'Почта кадровика'),
        ];
    }
}
